
# development:
#   adapter: sqlite3
#   database: lib/db/craft-beer-book
#   host: localhost
#   pool: 5
#   timeout: 5000

development: &default
  adapter: postgresql
  url: 'postgres://aifdsjjchuquau:899ecb3f742aeddf711d756c47c25a077a0ebf2dc10586e02426d60fe4d45e72@ec2-35-168-54-239.compute-1.amazonaws.com:5432/d18mqui8canebc
'
  database: mydb
  host: localhost
  pool: 5
  timeout: 5000
