
development:
  adapter: sqlite3
  database: lib/db/craft-beer-book
  host: localhost
  pool: 5
  timeout: 5000

production:
  url: <%= URI.ENV['DATABASE_URL']%>
  adapter: postgresql
  database: mydb
  host: localhost
  pool: 5
  timeout: 5000
